swagger: '2.0'
info: 
  version: 1.0.0
  title: Modcam Connector
produces: 
  - application/json
paths: 
  /peoplecounter/{deviceId}/{projection}/{startDate}/{endDate}:
    get: 
      parameters:
        - name: deviceId
          in: path
          required: true
          type: string
        - name: projection
          in: path
          required: true
          type: string
        - name: startDate
          in: path
          required: true
          type: string
          format: date
        - name: endDate
          in: path
          required: true
          type: string
          format: date
      responses: 
        200:
          description: People count
          schema: 
            properties:
              projection:
                type: string
              from:
                type: string
                format: date
              to:
                type: string
                format: date
              items:
                type: array
                items:
                  properties:
                    date:
                      type: string
                      format: date
                    in:
                      type: integer
                      format: int32
                    out:
                      type: integer
                      format: int32
